export {
  fetchBackendInfo,
  fetchCsrfToken,
  type BackendInfo,
} from './bootstrap.ts'
export {
  fetchAuthBootstrap,
  fetchCurrentUser,
  fetchUserList,
  login,
  logout,
  type AuthBootstrap,
  type CurrentUser,
  type LoginPayload,
  type LoginResult,
  type LogoutPayload,
  type PublicUser,
} from './auth.ts'
export {
  deleteCharacter,
  deleteLibraryDocument,
  deleteProjectManifest,
  applyWorldStateUpdates,
  ChatIntegrityError,
  checkChatCompletionStatus,
  fetchChatCompletionModels,
  fetchModelProviderModels,
  fetchModelProviders,
  checkNovelStatus,
  checkTextGenerationStatus,
  generateChatReply,
  generateChatReplyStream,
  generateStructuredOutput,
  type BackendConnectionStatus,
  createBackup,
  type ChatCompletionModelsPayload,
  type ChatCompletionStatusPayload,
  type DeleteCharacterPayload,
  type DeleteChatPayload,
  type DeleteLibraryDocumentPayload,
  type DeleteModelProviderPayload,
  type DeleteProjectManifestPayload,
  deleteChat,
  deleteModelProvider,
  duplicateChat,
  appendRuntimeLog,
  clearLogDocument,
  clearMemoryHits,
  clearTraceEntries,
  deleteNarrativeMemory,
  deleteNarrativeMemoryCandidate,
  exportChatTranscript,
  exportLibraryDocument,
  exportLogDocument,
  exportLogsBundle,
  exportProjectManifest,
  exportTraceEntries,
  type ExportChatPayload,
  type ExportLibraryDocumentPayload,
  fetchLogDocument,
  fetchCharacterChats,
  fetchCharacters,
  fetchChat,
  fetchLibraryDocuments,
  fetchProjectManifests,
  fetchWorldStateSnapshot,
  fetchEvalRuns,
  fetchMemoryHits,
  fetchSessionSummaries,
  fetchTraceEntries,
  fetchNarrativeMemoryCandidates,
  fetchNarrativeMemories,
  retrieveNarrativeMemories,
  retrieveGenerationContext,
  readSecret,
  extractNarrativeMemory,
  fetchSettings,
  fetchWorkspaceBootstrap,
  importProjectManifest,
  runLocalEval,
  saveCharacter,
  saveChat,
  saveLibraryDocument,
  saveModelProvider,
  saveProjectManifest,
  saveSettings,
  saveSessionSummary,
  deleteSessionSummary,
  saveSettingsWithSecret,
  setProjectPluginBinding,
  writeSecret,
  type AppSettings,
  type CharacterChatSummary,
  type CharacterChatsPayload,
  type CharacterSummary,
  type ChatCompletionMessage,
  type ChatMessage,
  type ChatPayload,
  type GenerateChatReplyPayload,
  type GenerateChatReplyStreamPayload,
  type FetchModelProviderModelsPayload,
  type StructuredOutputPayload,
  type LibraryDocument,
  type LogDocument,
  type LogDocumentPayload,
  type RuntimeLogPayload,
  type NarrativeMemoryExtractionPayload,
  type NarrativeMemoryExtractionResult,
  type NarrativeMemoryCandidateEntry,
  type NarrativeMemoryEntry,
  type NarrativeMemoryHitEntry,
  type NarrativeMemoryHitsPayload,
  type NarrativeMemoryMutationPayload,
  type NarrativeMemoryQueryPayload,
  type NarrativeMemoryRetrievePayload,
  type NarrativeMemoryRecord,
  type NarrativeTaskKind,
  type ModelProviderCapability,
  type ModelProviderCapabilityName,
  type ModelProviderModelsPayload,
  type ModelProviderRecord,
  type CharacterSnippet,
  type LorebookSnippet,
  type DirectiveSnippet,
  type EvalRunEntry,
  type EvalRunsPayload,
  type GenerationContextPayload,
  type GenerationContextResult,
  restoreBackup,
  rebuildWorldStateSnapshot,
  type BackupPayload,
  type KaiSettings,
  type NovelAiSettings,
  type ProjectManifestRecord,
  type ProjectPluginBindingPayload,
  type ReviewNarrativeMemoryCandidatePayload,
  type RenameChatPayload,
  renameChat,
  reviewNarrativeMemoryCandidate,
  type SecretPayload,
  type SaveChatPayload,
  type SaveCharacterPayload,
  type SaveLibraryDocumentPayload,
  type SaveModelProviderPayload,
  type SaveProjectManifestPayload,
  type SaveSettingsPayload,
  type SaveSessionSummaryPayload,
  type DeleteSessionSummaryPayload,
  type SaveSettingsWithSecretPayload,
  type SessionSummariesPayload,
  type SessionSummary,
  type SettingsPayload,
  type TextGenerationStatusPayload,
  type TraceContextPayload,
  type TraceContextBudgetDebug,
  type TraceEntriesPayload,
  type TraceEntry,
  type TextGenerationWebUiSettings,
  type RetrievalHitEntry,
  type RetrievalHitSummary,
  type RetrievalHitsPayload,
  type RetrievalJobEntry,
  type RetrievalJobsPayload,
  type StructuredSchemaId,
  type SessionSnippet,
  type WorldStateSnippet,
  type WorldStateItemEntry,
  type WorldStateSnapshotEntry,
  type WorldStateSnapshotPayload,
  type RebuildWorldStatePayload,
  type WorldStateUpdateRecord,
  type ApplyWorldStateUpdatesPayload,
  type WriteSecretPayload,
  type WorkspaceBootstrap,
  fetchWorkspaceCatalog,
  fetchRetrievalHits,
  fetchRetrievalJobs,
  type WorkspaceCatalogEntry,
  type WorkspaceCatalogPayload,
} from './workspace.ts'
export {
  request,
  requestJson,
  requestText,
  requestVoid,
  type JsonMethod,
  type JsonRequestOptions,
} from './request.ts'
export {
  requestStream,
  type StreamChunk,
  type StreamChunkCallback,
  type StreamRequestOptions,
} from './http/request-stream.ts'

export {
  clearTauriAvatarSrcCache,
  isTauriDesktop,
  peekTauriAvatarSrcCache,
  resolveTauriAvatarSrc,
  subscribeTauriAvatarSrcInvalidation,
  tauriInvoke,
} from './tauri.ts'
export {
  AppUpdateHandle,
  checkForAppUpdate,
  getAppVersion,
  type AppUpdateDownloadEvent,
  type AppUpdateMetadata,
} from './updater.ts'
